import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    function generate(colors) {
        if (!colors)
            return

        const hex = color => color.toString()
        const rgb = color => `${Math.round(color.r * 255)}, ${Math.round(color.g * 255)}, ${Math.round(color.b * 255)}`
        const css = `/* Generated by AMBXST. */
:root {
    --SystemAccentColor: ${hex(colors.primary)} !important;
    --SystemAccentColor-RGB: ${rgb(colors.primary)} !important;
    --SystemAccentColorAccent: ${hex(colors.primary)} !important;
    --SystemAccentColorAccent-RGB: ${rgb(colors.primary)} !important;
    --SystemAccentColorLight1: ${hex(colors.primaryFixedDim)} !important;
    --SystemAccentColorLight1-RGB: ${rgb(colors.primaryFixedDim)} !important;
    --SystemAccentColorLight2: ${hex(colors.primaryFixed)} !important;
    --SystemAccentColorLight2-RGB: ${rgb(colors.primaryFixed)} !important;
    --SystemAccentColorLight3: ${hex(colors.overPrimaryContainer)} !important;
    --SystemAccentColorLight3-RGB: ${rgb(colors.overPrimaryContainer)} !important;
    --SystemAccentColorDark1: ${hex(colors.primaryContainer)} !important;
    --SystemAccentColorDark1-RGB: ${rgb(colors.primaryContainer)} !important;

    --minimal_dark_color: ${hex(colors.primary)} !important;
    --minimal_dark_color_rgb: ${rgb(colors.primary)} !important;
    --minimal_dark_color1: ${hex(colors.primary)} !important;
    --minimal_dark_color_rgb1: ${rgb(colors.primary)} !important;
    --minimal_dark_be_grey: ${hex(colors.outlineVariant)} !important;
    --minimal_dark_black: ${hex(colors.surface)} !important;
    --minimal_dark_blacker: ${hex(colors.surfaceContainerLowest)} !important;
    --minimal_dark_blacker_alt: ${hex(colors.background)} !important;
    --minimal_dark_blacker_alt1: ${hex(colors.surfaceDim)} !important;
    --minimal_dark_blacker_alt2: ${hex(colors.shadow)} !important;
    --minimal_dark_topgrey: ${hex(colors.outline)} !important;
    --minimal_dark_topgrey1: ${hex(colors.overSurfaceVariant)} !important;
    --minimal_dark_greyblack: ${hex(colors.surfaceContainerHigh)} !important;
    --minimal_dark_invisiblegrey: rgba(${rgb(colors.surfaceContainerHigh)}, .25) !important;
    --minimal_dark_browser_overlay_close: ${hex(colors.green)} !important;
    --minimal_dark_red2: ${hex(colors.error)} !important;
    --minimal_dark_red2_rgba: ${rgb(colors.error)}, 1 !important;
    --minimal_dark_redsettings: ${hex(colors.error)} !important;
    --minimal_dark_greensettings: ${hex(colors.green)} !important;
    --minimal_dark_status_green: ${hex(colors.green)} !important;
    --minimal_dark_less_white: ${hex(colors.overBackground)} !important;
    --minimal_dark_progress_bar: ${hex(colors.primary)} !important;
    --minimal_dark_currency: ${hex(colors.overSurface)} !important;
    --minimal_dark_installed_games: ${hex(colors.secondary)} !important;
    --minimal_dark_bgb: radial-gradient(circle, ${hex(colors.blue)} 0%, ${hex(colors.blueContainer)} 100%) !important;
    --minimal_dark_bgg: radial-gradient(circle, ${hex(colors.green)} 0%, ${hex(colors.greenContainer)} 80%) !important;
}
`
        const path = Quickshell.env("HOME") + "/.config/millennium/quick.css"

        writerProcess.command = ["sh", "-c", `printf '%s' "${css}" > "${path}"`]
        writerProcess.running = true
    }

    property Process writerProcess: Process {
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("MillenniumGenerator: Theme generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: error => {
                if (error)
                    console.error("MillenniumGenerator Error:", error)
            }
        }
    }
}
