-- Compositor for the AMBXST greeter, run by greetd as the `greeter` user.
-- install.sh appends the user's own hl.monitor() blocks below, so the greeter
-- and the desktop drive the monitors identically and the hand-off needs no
-- modeset (a modeset is what blanks the screen for seconds on some monitors).

hl.config({
    input = {
        kb_layout = "de",
        numlock_by_default = true,
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "rgb(000000)",
    },
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

hl.on("hyprland.start", function()
    -- When the greeter quits (after launching the session, or on a crash)
    -- the compositor exits too, handing the VT back to greetd.
    -- (Lua-config Hyprland takes the dispatcher as Lua: `hl.dsp.exit()`.)
    hl.exec_cmd([[sh -c "qs -p /usr/share/ambxst-greeter/shell.qml; hyprctl dispatch 'hl.dsp.exit()'"]])
end)

-- MONITORS (generated by install.sh)
